[metadata]
name = "bucle"
preprompt = " "
postprompt = " "

[agents.codex]
cmd = "codex exec {{prompt}}"

[agents.codexmini]
cmd = "codex exec --model gpt-5.4-mini -c model_reasoning_effort=low {{prompt}}"

[agents.bigpickle]
cmd = "opencode run --model opencode/big-pickle {{prompt}}"

[agents.opencode]
cmd = "opencode run --model openai/gpt-5.5 {{prompt}}"

## we need to include some sort of git integration but we are not sure how to do it, we could do it in the agent itself, but maybe it's better to do it in the tool. For instance, after every task, we could commit the changes with a random message. We could even generate the commit message with the external LLM handled by bucle itself, for instance, we could have a API call like "generate commit message" that would take as input the name of the task and the status (success or failure) and then it would generate a commit message that we could use for the commit.


[[tasks]]
name = "bucle-factorize-helpers"
agent = "opencode"
prompt = """
I see that the cli script is really long and it has become hard to maintain.

Can we start factorizing things?

First i would like to have a module for helper functions.

Examples:
- format_utc_timestamp
- safe_filename
- is_mapping

Also check for more helper functions and include them in this file.
"""
status = "success"

[[tasks]]
name = "bucle-init-command-justfile"
agent = "opencode"
prompt = """
For the bucle init command, we should also check if there is a Justfile in the directory where we are running it. If there is one, then append a rule to the Justfile. If there is none, do nothing.

It should be smth like:

# runs bucle tasks
bucle:
    bucle run --reverse -v

# lists bucle tasks
bucle-list:
    bucle list

"""
status = "success"

[[tasks]]
name = "bucle-factorize-templates"
agent = "opencode"
prompt = """
I see that now the HTML templates for the render command are embedded in the cli script. Can we move them somewhere else?
src/bucle/cli.py:639-1033

- I want them to be downloaded together with the installation (see README.md:7-26).
- I want them to be their own files, with extension .html.jinja2
"""
status = "success"

[[tasks]]
name = "bucle-render-commad"
agent = "codex"
prompt = """
I want to include a render subcommand, this should read the .bucle .toml file, and parse the .bucle/ folder. Then for the entire list of tasks it shouldl render a HTML file (use a template and jinja2). The HTML file should contain the name of the task and the prompt, status, agent etc.

For each log file in the .bucle directory we should also render a basic HTML, much simpler, and locate it in the same folder with the same name, just .html extension. The contents of the file should be MONO font but there should be some header that tells us about the task name and date, everything should be extractible from the filename.

In addition to the info already present in the TOML file, the main page should also include the log files. This should be in a dropdown menu in each task "card". This log files should contain two botton options, a copy path button and a visualize button. The visualize one should lead to the HTML file rendered for that log file, and the copy path should copy the path of the log file to the clipboard.

"""
status = "success"

[[tasks]]
name = "bucle-init-command"
agent = "opencode"
prompt = """
I want to include a init subcommand, this should create a empty .bucle folder, append the .bucle folder to the .gitignore (fail if there is no gitignore file) and then create a small .bucle.toml file with the basic structure and a couple of tasks. Get inspiration from the task1, 2 and 3 in this repository.
"""
status = "success"

[[tasks]]
name = "add-install-from-gitrepo"
agent = "opencode"
prompt = """
README.md:8-12

This installation is not great because it s in clone first and install later for development. I want to improve the installation script to include the option to install driectly from git. I have no repo yest but I want to have the placeholder git.repo.git/davidmasp/bucle.

Use the uv tool installation from a git URL.

Leave the local instructions but include a "git clone" command too.

"""
status = "success"


[[tasks]]
name = "limit-flag"
agent = "opencode"
prompt = """
add a limit flag into the bucle list and bucle run command. This should contain a integer number. When using the flag, the execution should limit, either the listed number of tasks or the number of executed files to this number.

In the run mode, ideally I want to do this after the re-ordering of the tasks, so first i would either reverse them or shuffle them and after that limit to the first XX from the limit flag.
"""
status = "success"

[[tasks]]
name = "json-to-list"
agent = "opencode"
prompt = """
I need to change the way the agent reports the success of failures of the task. Currently it tries to re-create the json file but there are issues when the first task is already in the file, sometimes it deletes it. I want the agent to append into a list instead. Using a echo command. For instance, echo "name of task" >> .bucle/success.txt or for failure we should do echo "<name of task>,<failure reason>" >> .bucle/failure.txt.

The rest of the logic stays the same so the bucle tool will remove the failure/success files after every run.
"""
status = "success"

[[tasks]]
name = "shuffle-flag"
agent = "opencode"
prompt = """
Create a shuffle order, so instead of reverse or normal order the tasks are passed through in a random order. the rest of the logic stays the same.

The name of the flag is --shuffle
"""
status = "success"

[[tasks]]
name = "task3"
agent = "bigpickle"
prompt = "this task is a test to fail, report failure and exit"
auto-reset = true
status = "failure"
failure_reason = "test task designed to fail"

[[tasks]]
name = "task2"
agent = "bigpickle"
prompt = "say hi!"
auto-reset = true
status = "success"

[[tasks]]
name = "task1"
agent = "bigpickle"
prompt = "say bye!"
auto-reset = true
status = "success"

[[tasks]]
name = "add-list-alias"
agent = "opencode"
prompt = "I want to add a subcommand alias to tasks, essentially if we run bucle list should have the same behaviour than bucle tasks"
status = "success"


[[tasks]]
name = "remove-prompt-from-list"
agent = "opencode"
prompt = "When listing the tasks in list, i don't want to include the prompt, keep all other fields but remove the prompt text itself."
status = "success"

[[tasks]]
name = "reverse-mode"
agent = "opencode"
prompt = "in the bucle run command, add a --reverse flag. If true, the first task to implement will be the last in the list."
status = "success"


[[tasks]]
name = "more-verbose"
agent = "opencode"
prompt = "I need to be more verbose when launching a task, for now something similar would be fine, include the name of the task that got launched, the path of the log file and the X out of Y tasks. If rich library includes a spinner, also add it to the mix. I want the runner option"
status = "success"

[[tasks]]
name = "auto-reset-tasks"
agent = "opencode"
prompt = """

I want to add an extra argument value in the task definition. This will be a optional argument so it's not mandatory for the task.

This extra value will be "auto-reset" and it will mean that a particular task is auto-reset when invoking the commad uv run bucle reset (wiht the additional flag --auto)

"""
status = "success"

[[tasks]]
name = "readme-update"
agent = "bigpickle"
prompt = "Check the codebase of this folder, then read the README file. Update it according to the newer functionality available"
status = "success"
